<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net48</TargetFrameworks>
		<Nullable>enable</Nullable>
		<UseWindowsForms>False</UseWindowsForms>
		<ProduceReferenceAssembly>False</ProduceReferenceAssembly>
		<IsPublishable>False</IsPublishable>
		<EnableUnsafeBinaryFormatterSerialization>True</EnableUnsafeBinaryFormatterSerialization>
		<LangVersion>latest</LangVersion>
		<NoWarn>CS0115;CS0618</NoWarn>
		<RootNamespace>GTKWinFormsApp</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Properties\AssemblyInfo.cs" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\010.jpg">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\BindingNavigator.Delete.ico">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\img10.jpg">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\img11.jpg">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\timg.jpg">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\timg2.jpg">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\timg6.jpg">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="工程说明.txt" />
		<None Include="TestData1.en.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="TestData1.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<Compile Update="UserControl11.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="UserControl11.Designer.cs">
			<DependentUpon>UserControl11.cs</DependentUpon>
		</Compile>
		<EmbeddedResource Update="UserControl11.resx">
			<DependentUpon>UserControl11.cs</DependentUpon>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Form1.cs" SubType="Form" />
		<Compile Update="Properties\Resources.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Form1.resx" />
		<EmbeddedResource Update="Properties\Resources.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>Resources.Designer.cs</LastGenOutput>
		  <CustomToolNamespace>GTKWinFormsApp.Properties</CustomToolNamespace>
		</EmbeddedResource>
		<EmbeddedResource Update="Properties\Resources.zh-HANS.resx">
			<DependentUpon>Resources.resx</DependentUpon>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Form2.cs" SubType="Form" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Form2.resx" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Form3.cs" SubType="Form" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Form3.resx" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Form4.cs" SubType="Form" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Form4.resx" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\..\Source\GTKSystem.Windows.Forms\Content\System.ComponentModel.cs" />
		<Compile Include="..\..\Source\GTKSystem.Windows.Forms\Content\System.Resources.ResourceManager.cs" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="System.Drawing" Aliases="sd" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="GtkSharp" Version="3.24.24.95">
		  <IncludeAssets>all</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Resources.Extensions" Version="8.0.0" Aliases="sre" PrivateAssets="All" IncludeAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="System.Drawing" PrivateAssets="All" IncludeAssets="All" Condition="'$(TargetFramework)'=='net4.8'" Aliases="sd" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Source\GTKSystem.Windows.Forms\GTKSystem.Windows.Forms.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Update="System.Drawing">
	    <Aliases>sd</Aliases>
	  </Reference>
	</ItemGroup>

</Project>