<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>False</UseWindowsForms>
		<ProduceReferenceAssembly>False</ProduceReferenceAssembly>
		<IsPublishable>False</IsPublishable>
		<EnableUnsafeBinaryFormatterSerialization>True</EnableUnsafeBinaryFormatterSerialization>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="工程说明.txt" />
		<None Remove="工程说明.txt" />
		<Content Include="工程说明.txt" Link="ProjectDescription.zh-HANS.txt" />
		<None Include="TestData1.en.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="TestData1.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Form1.cs" />
		<Compile Remove="Form1.Designer.cs" />
		<Compile Include="Form1.cs" Link="TestDataForm.cs" SubType="Form" />
		<Compile Include="Form1.Designer.cs" Link="TestDataForm.Designer.cs" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Remove="Form1.resx" />
		<EmbeddedResource Include="Form1.resx" Link="TestDataForm.resx" />
		<EmbeddedResource Update="Properties\Resources.de.resx">
		  <DependentUpon>Resources.resx</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="Properties\Resources.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>Resources.Designer.cs</LastGenOutput>
		  <CustomToolNamespace>GTKWinFormsApp.Properties</CustomToolNamespace>
		</EmbeddedResource>
		<EmbeddedResource Update="Properties\Resources.zh-HANS.resx">
			<DependentUpon>Resources.resx</DependentUpon>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Form2.cs" />
		<Compile Remove="Form2.Designer.cs" />
		<Compile Include="Form2.cs" Link="ListViewForm.cs" SubType="Form" />
		<Compile Include="Form2.Designer.cs" Link="ListViewForm.Designer.cs" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Remove="Form2.resx" />
		<EmbeddedResource Include="Form2.resx" Link="ListViewForm.resx" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Form3.cs" />
		<Compile Remove="Form3.Designer.cs" />
		<Compile Include="Form3.cs" Link="GtkMainForm.cs" SubType="Form" />
		<Compile Include="Form3.Designer.cs" Link="GtkMainForm.Designer.cs" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Remove="Form3.resx" />
		<EmbeddedResource Include="Form3.resx" Link="GtkMainForm.resx" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Form4.cs" />
		<Compile Remove="Form4.Designer.cs" />
		<Compile Include="Form4.cs" Link="CommonDialogsForm.cs" SubType="Form" />
		<Compile Include="Form4.Designer.cs" Link="CommonDialogsForm.Designer.cs" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Remove="Form4.resx" />
		<EmbeddedResource Include="Form4.resx" Link="CommonDialogsForm.resx" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\..\Source\GTKSystem.Windows.Forms\Content\System.ComponentModel.cs" Link="System.ComponentModel.cs" />
		<Compile Include="..\..\Source\GTKSystem.Windows.Forms\Content\System.Resources.ResourceManager.cs" Link="System.Resources.ResourceManager.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="GtkSharp" Version="3.24.24.95" />
		<PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.14" Aliases="sdc" PrivateAssets="All" IncludeAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Form2.cs" />
		<Compile Update="Properties\Resources.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Source\GTKSystem.Windows.Forms\GTKSystem.Windows.Forms.csproj" />
	</ItemGroup>

</Project>