using System.Diagnostics;

namespace System.Drawing;

using GtkKnownColor = KnownColor;

internal class GtkColorTable
{
    internal static Dictionary<GtkKnownColor, uint> ArgbValues;

    static GtkColorTable()
    {
        ArgbValues = new Dictionary<GtkKnownColor, uint>();
        foreach (var kvp in new KeyValuePair<GtkKnownColor, uint>[]
                 {
                     new(GtkKnownColor.ActiveBorder, 0xFFD4D0C8),
                     new(GtkKnownColor.ActiveCaption, 0xFF0054E3),
                     new(GtkKnownColor.ActiveCaptionText, 0xFFFFFFFF),
                     new(GtkKnownColor.AliceBlue, 0xFFF0F8FF),
                     new(GtkKnownColor.AntiqueWhite, 0xFFFAEBD7),
                     new(GtkKnownColor.AppWorkspace, 0xFF808080),
                     new(GtkKnownColor.Aqua, 0xFF00FFFF),
                     new(GtkKnownColor.Aquamarine, 0xFF7FFFD4),
                     new(GtkKnownColor.Azure, 0xFFF0FFFF),
                     new(GtkKnownColor.Beige, 0xFFF5F5DC),
                     new(GtkKnownColor.Bisque, 0xFFFFE4C4),
                     new(GtkKnownColor.Black, 0xFF000000),
                     new(GtkKnownColor.BlanchedAlmond, 0xFFFFEBCD),
                     new(GtkKnownColor.Blue, 0xFF0000FF),
                     new(GtkKnownColor.BlueViolet, 0xFF8A2BE2),
                     new(GtkKnownColor.Brown, 0xFFA52A2A),
                     new(GtkKnownColor.BurlyWood, 0xFFDEB887),
                     new(GtkKnownColor.ButtonFace, 0xFFECE9D8),
                     new(GtkKnownColor.ButtonHighlight, 0xFFFFFFFF),
                     new(GtkKnownColor.ButtonShadow, 0xFFACA899),
                     new(GtkKnownColor.CadetBlue, 0xFF5F9EA0),
                     new(GtkKnownColor.Chartreuse, 0xFF7FFF00),
                     new(GtkKnownColor.Chocolate, 0xFFD2691E),
                     new(GtkKnownColor.Control, 0xFFECE9D8),
                     new(GtkKnownColor.ControlDark, 0xFFACA899),
                     new(GtkKnownColor.ControlDarkDark, 0xFF716F64),
                     new(GtkKnownColor.ControlLight, 0xFFF1EFE2),
                     new(GtkKnownColor.ControlLightLight, 0xFFFFFFFF),
                     new(GtkKnownColor.ControlText, 0xFF000000),
                     new(GtkKnownColor.Coral, 0xFFFF7F50),
                     new(GtkKnownColor.CornflowerBlue, 0xFF6495ED),
                     new(GtkKnownColor.Cornsilk, 0xFFFFF8DC),
                     new(GtkKnownColor.Crimson, 0xFFDC143C),
                     new(GtkKnownColor.Cyan, 0xFF00FFFF),
                     new(GtkKnownColor.DarkBlue, 0xFF00008B),
                     new(GtkKnownColor.DarkCyan, 0xFF008B8B),
                     new(GtkKnownColor.DarkGoldenrod, 0xFFB8860B),
                     new(GtkKnownColor.DarkGray, 0xFFA9A9A9),
                     new(GtkKnownColor.DarkGreen, 0xFF006400),
                     new(GtkKnownColor.DarkKhaki, 0xFFBDB76B),
                     new(GtkKnownColor.DarkMagenta, 0xFF8B008B),
                     new(GtkKnownColor.DarkOliveGreen, 0xFF556B2F),
                     new(GtkKnownColor.DarkOrange, 0xFFFF8C00),
                     new(GtkKnownColor.DarkOrchid, 0xFF9932CC),
                     new(GtkKnownColor.DarkRed, 0xFF8B0000),
                     new(GtkKnownColor.DarkSalmon, 0xFFE9967A),
                     new(GtkKnownColor.DarkSeaGreen, 0xFF8FBC8B),
                     new(GtkKnownColor.DarkSlateBlue, 0xFF483D8B),
                     new(GtkKnownColor.DarkSlateGray, 0xFF2F4F4F),
                     new(GtkKnownColor.DarkTurquoise, 0xFF00CED1),
                     new(GtkKnownColor.DarkViolet, 0xFF9400D3),
                     new(GtkKnownColor.DeepPink, 0xFFFF1493),
                     new(GtkKnownColor.DeepSkyBlue, 0xFF00BFFF),
                     new(GtkKnownColor.Desktop, 0xFF004E98),
                     new(GtkKnownColor.DimGray, 0xFF696969),
                     new(GtkKnownColor.DodgerBlue, 0xFF1E90FF),
                     new(GtkKnownColor.Firebrick, 0xFFB22222),
                     new(GtkKnownColor.FloralWhite, 0xFFFFFAF0),
                     new(GtkKnownColor.ForestGreen, 0xFF228B22),
                     new(GtkKnownColor.Fuchsia, 0xFFFF00FF),
                     new(GtkKnownColor.Gainsboro, 0xFFDCDCDC),
                     new(GtkKnownColor.GhostWhite, 0xFFF8F8FF),
                     new(GtkKnownColor.Gold, 0xFFFFD700),
                     new(GtkKnownColor.Goldenrod, 0xFFDAA520),
                     new(GtkKnownColor.GradientActiveCaption, 0xFF3D95FF),
                     new(GtkKnownColor.GradientInactiveCaption, 0xFF9DB9EB),
                     new(GtkKnownColor.Gray, 0xFF808080),
                     new(GtkKnownColor.GrayText, 0xFFACA899),
                     new(GtkKnownColor.Green, 0xFF008000),
                     new(GtkKnownColor.GreenYellow, 0xFFADFF2F),
                     new(GtkKnownColor.Highlight, 0xFF316AC5),
                     new(GtkKnownColor.HighlightText, 0xFFFFFFFF),
                     new(GtkKnownColor.Honeydew, 0xFFF0FFF0),
                     new(GtkKnownColor.HotPink, 0xFFFF69B4),
                     new(GtkKnownColor.HotTrack, 0xFF000080),
                     new(GtkKnownColor.InactiveBorder, 0xFFD4D0C8),
                     new(GtkKnownColor.InactiveCaption, 0xFF7A96DF),
                     new(GtkKnownColor.InactiveCaptionText, 0xFFD8E4F8),
                     new(GtkKnownColor.IndianRed, 0xFFCD5C5C),
                     new(GtkKnownColor.Indigo, 0xFF4B0082),
                     new(GtkKnownColor.Info, 0xFFFFFFE1),
                     new(GtkKnownColor.InfoText, 0xFF000000),
                     new(GtkKnownColor.Ivory, 0xFFFFFFF0),
                     new(GtkKnownColor.Khaki, 0xFFF0E68C),
                     new(GtkKnownColor.Lavender, 0xFFE6E6FA),
                     new(GtkKnownColor.LavenderBlush, 0xFFFFF0F5),
                     new(GtkKnownColor.LawnGreen, 0xFF7CFC00),
                     new(GtkKnownColor.LemonChiffon, 0xFFFFFACD),
                     new(GtkKnownColor.LightBlue, 0xFFADD8E6),
                     new(GtkKnownColor.LightCoral, 0xFFF08080),
                     new(GtkKnownColor.LightCyan, 0xFFE0FFFF),
                     new(GtkKnownColor.LightGoldenrodYellow, 0xFFFAFAD2),
                     new(GtkKnownColor.LightGray, 0xFFD3D3D3),
                     new(GtkKnownColor.LightGreen, 0xFF90EE90),
                     new(GtkKnownColor.LightPink, 0xFFFFB6C1),
                     new(GtkKnownColor.LightSalmon, 0xFFFFA07A),
                     new(GtkKnownColor.LightSeaGreen, 0xFF20B2AA),
                     new(GtkKnownColor.LightSkyBlue, 0xFF87CEFA),
                     new(GtkKnownColor.LightSlateGray, 0xFF778899),
                     new(GtkKnownColor.LightSteelBlue, 0xFFB0C4DE),
                     new(GtkKnownColor.LightYellow, 0xFFFFFFE0),
                     new(GtkKnownColor.Lime, 0xFF00FF00),
                     new(GtkKnownColor.LimeGreen, 0xFF32CD32),
                     new(GtkKnownColor.Linen, 0xFFFAF0E6),
                     new(GtkKnownColor.Magenta, 0xFFFF00FF),
                     new(GtkKnownColor.Maroon, 0xFF800000),
                     new(GtkKnownColor.MediumAquamarine, 0xFF66CDAA),
                     new(GtkKnownColor.MediumBlue, 0xFF0000CD),
                     new(GtkKnownColor.MediumOrchid, 0xFFBA55D3),
                     new(GtkKnownColor.MediumPurple, 0xFF9370DB),
                     new(GtkKnownColor.MediumSeaGreen, 0xFF3CB371),
                     new(GtkKnownColor.MediumSlateBlue, 0xFF7B68EE),
                     new(GtkKnownColor.MediumSpringGreen, 0xFF00FA9A),
                     new(GtkKnownColor.MediumTurquoise, 0xFF48D1CC),
                     new(GtkKnownColor.MediumVioletRed, 0xFFC71585),
                     new(GtkKnownColor.Menu, 0xFFFFFFFF),
                     new(GtkKnownColor.MenuBar, 0xFFECE9D8),
                     new(GtkKnownColor.MenuHighlight, 0xFF316AC5),
                     new(GtkKnownColor.MenuText, 0xFF000000),
                     new(GtkKnownColor.MidnightBlue, 0xFF191970),
                     new(GtkKnownColor.MintCream, 0xFFF5FFFA),
                     new(GtkKnownColor.MistyRose, 0xFFFFE4E1),
                     new(GtkKnownColor.Moccasin, 0xFFFFE4B5),
                     new(GtkKnownColor.NavajoWhite, 0xFFFFDEAD),
                     new(GtkKnownColor.Navy, 0xFF000080),
                     new(GtkKnownColor.OldLace, 0xFFFDF5E6),
                     new(GtkKnownColor.Olive, 0xFF808000),
                     new(GtkKnownColor.OliveDrab, 0xFF6B8E23),
                     new(GtkKnownColor.Orange, 0xFFFFA500),
                     new(GtkKnownColor.OrangeRed, 0xFFFF4500),
                     new(GtkKnownColor.Orchid, 0xFFDA70D6),
                     new(GtkKnownColor.PaleGoldenrod, 0xFFEEE8AA),
                     new(GtkKnownColor.PaleGreen, 0xFF98FB98),
                     new(GtkKnownColor.PaleTurquoise, 0xFFAFEEEE),
                     new(GtkKnownColor.PaleVioletRed, 0xFFDB7093),
                     new(GtkKnownColor.PapayaWhip, 0xFFFFEFD5),
                     new(GtkKnownColor.PeachPuff, 0xFFFFDAB9),
                     new(GtkKnownColor.Peru, 0xFFCD853F),
                     new(GtkKnownColor.Pink, 0xFFFFC0CB),
                     new(GtkKnownColor.Plum, 0xFFDDA0DD),
                     new(GtkKnownColor.PowderBlue, 0xFFB0E0E6),
                     new(GtkKnownColor.Purple, 0xFF800080),
                     new(GtkKnownColor.Red, 0xFFFF0000),
                     new(GtkKnownColor.RosyBrown, 0xFFBC8F8F),
                     new(GtkKnownColor.RoyalBlue, 0xFF4169E1),
                     new(GtkKnownColor.SaddleBrown, 0xFF8B4513),
                     new(GtkKnownColor.Salmon, 0xFFFA8072),
                     new(GtkKnownColor.SandyBrown, 0xFFF4A460),
                     new(GtkKnownColor.ScrollBar, 0xFFD4D0C8),
                     new(GtkKnownColor.SeaGreen, 0xFF2E8B57),
                     new(GtkKnownColor.SeaShell, 0xFFFFF5EE),
                     new(GtkKnownColor.Sienna, 0xFFA0522D),
                     new(GtkKnownColor.Silver, 0xFFC0C0C0),
                     new(GtkKnownColor.SkyBlue, 0xFF87CEEB),
                     new(GtkKnownColor.SlateBlue, 0xFF6A5ACD),
                     new(GtkKnownColor.SlateGray, 0xFF708090),
                     new(GtkKnownColor.Snow, 0xFFFFFAFA),
                     new(GtkKnownColor.SpringGreen, 0xFF00FF7F),
                     new(GtkKnownColor.SteelBlue, 0xFF4682B4),
                     new(GtkKnownColor.Tan, 0xFFD2B48C),
                     new(GtkKnownColor.Teal, 0xFF008080),
                     new(GtkKnownColor.Thistle, 0xFFD8BFD8),
                     new(GtkKnownColor.Tomato, 0xFFFF6347),
                     new(GtkKnownColor.Transparent, 0x00000000),
                     new(GtkKnownColor.Transparent, 0x00FFFFFF),
                     new(GtkKnownColor.Turquoise, 0xFF40E0D0),
                     new(GtkKnownColor.Violet, 0xFFEE82EE),
                     new(GtkKnownColor.Wheat, 0xFFF5DEB3),
                     new(GtkKnownColor.White, 0xFFFFFFFF),
                     new(GtkKnownColor.WhiteSmoke, 0xFFF5F5F5),
                     new(GtkKnownColor.Window, 0xFFFFFFFF),
                     new(GtkKnownColor.WindowFrame, 0xFF000000),
                     new(GtkKnownColor.WindowText, 0xFF000000),
                     new(GtkKnownColor.Yellow, 0xFFFFFF00),
                     new(GtkKnownColor.YellowGreen, 0xFF9ACD32)
                 })
        {
            try
            {
                if (!ArgbValues.ContainsKey(kvp.Key))
                {
                    ArgbValues.Add(kvp.Key, kvp.Value);
                }
            }
            catch (Exception e)
            {
                Trace.WriteLine(e);
            }
        }
    }
}